#!/usr/bin/env bash
alias music='baton'
alias mytracks='music me saved tracks'
alias saved='mytracks'
alias liked='saved'
alias next='music next'
alias prev='music prev'
alias previous='prev'
alias like='music save'
alias curr='music status'
